Watching for file changes with StatReloader
[17/Oct/2023 17:20:57] "GET / HTTP/1.1" 200 10664
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 17, 2023 - 17:20:43
Django version 4.2.6, using settings 'ecommerce01.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:24:26] "GET / HTTP/1.1" 400 63055
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[17/Oct/2023 17:24:27] "GET /favicon.ico HTTP/1.1" 400 62975
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:25:38] "GET / HTTP/1.1" 400 62918
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[17/Oct/2023 17:25:39] "GET /favicon.ico HTTP/1.1" 400 62975
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:25:49] "GET / HTTP/1.1" 400 63055
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[17/Oct/2023 17:25:49] "GET /favicon.ico HTTP/1.1" 400 62975
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:26:57] "GET / HTTP/1.1" 400 63055
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[17/Oct/2023 17:26:57] "GET /favicon.ico HTTP/1.1" 400 62975
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:27:16] "GET / HTTP/1.1" 400 63192
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:27:16] "GET / HTTP/1.1" 400 62918
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[17/Oct/2023 17:27:17] "GET /favicon.ico HTTP/1.1" 400 62975
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:27:33] "GET / HTTP/1.1" 400 63055
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[17/Oct/2023 17:27:33] "GET /favicon.ico HTTP/1.1" 400 62975
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:28:36] "GET / HTTP/1.1" 400 63192
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:28:38] "GET / HTTP/1.1" 400 62918
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[17/Oct/2023 17:28:38] "GET /favicon.ico HTTP/1.1" 400 62975
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /
[17/Oct/2023 17:28:43] "GET / HTTP/1.1" 400 63055
Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/dev/venvdjdev01/lib64/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.165.47.144:8000'. You may need to add '54.165.47.144' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[17/Oct/2023 17:28:43] "GET /favicon.ico HTTP/1.1" 400 62975
[17/Oct/2023 17:28:59] "GET / HTTP/1.1" 200 10664
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 17, 2023 - 17:26:54
Django version 4.2.6, using settings 'ecommerce01.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

